AllCops:
  Exclude:
    - Rakefile
    - bin/*

Metrics/LineLength:
  Enabled: true
  Max: 80

Style/Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/ConditionPosition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case
  SupportedStyles:
  - snake_case
  - normalcase
  - non_integer

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
  - 'test/**/*.rb'
  - 'Rakefile'
  - '**/*.rake'

Metrics/ClassLength:
  CountComments: false
  Exclude:
  - 'test/**/*.rb'

Metrics/MethodLength:
  Enabled: true
  Exclude:
  - 'test/**/*.rb'

Metrics/ModuleLength:
  CountComments: false
  Exclude:
  - 'test/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
